

CREATE VIEW product_prices AS
SELECT product_id, product_name, unit_price
FROM products;


CREATE VIEW top_10_products AS
SELECT 
    product_id,
    product_name,
    unit_price
FROM products
ORDER BY unit_price DESC
LIMIT 10;

--1.--

---LIST ALL PRODUCTS WITH CATEGORY NAMES--

SELECT
	PRODUCT_ID,
	PRODUCT_NAME,
	ROUND(UNIT_PRICE) AS PRICE,
	CATEGORY_NAME
FROM
	PRODUCTS
	JOIN CATEGORIES USING (CATEGORY_ID)
ORDER BY
	PRODUCT_NAME;



---COUNT THE NUMBER OF CUSTOMERS BY COUNTRY--

SELECT
	COUNTRY,
	COUNT(*) AS TOTAL_CUSTOMERS
FROM
	CUSTOMERS
GROUP BY
	COUNTRY
ORDER BY
	TOTAL_CUSTOMERS DESC;



	--TOTAL NUMBER OF ORDERS PER EMPLOYEE--
	
SELECT
	E.EMPLOYEE_ID,
	CONCAT(E.FIRST_NAME, ' ', E.LAST_NAME) AS EMPLOYEE_NAME,
	COUNT(O.ORDER_ID) AS TOTAL_ORDERS
FROM
	EMPLOYEES AS E
	JOIN ORDERS AS O ON E.EMPLOYEE_ID = O.EMPLOYEE_ID
GROUP BY
	E.EMPLOYEE_ID,
	EMPLOYEE_NAME
ORDER BY
	TOTAL_ORDERS DESC;


	--ORDERS BY YEAR--

	SELECT
	EXTRACT(
		YEAR
		FROM
			ORDER_DATE
	) AS ORDER_YEAR,
	COUNT(*) AS TOTAL_ORDERS
FROM
	ORDERS
GROUP BY
	ORDER_YEAR
ORDER BY
	ORDER_YEAR DESC;


	--2--

	--MONTHLY REVENUE--
	SELECT
	DATE_TRUNC('month', O.ORDER_DATE) AS MONTH,
	ROUND(
		SUM(OD.UNIT_PRICE * OD.QUANTITY * (1 - OD.DISCOUNT))
	) AS TOTAL_REVENUE
FROM
	ORDERS AS O
	JOIN ORDER_DETAILS AS OD ON O.ORDER_ID = OD.ORDER_ID
GROUP BY
	MONTH
ORDER BY
	MONTH DESC;


---TOP 10 PRODUCTS BY REVENUE---
SELECT
	P.PRODUCT_NAME,
	ROUND(
		SUM(OD.UNIT_PRICE * OD.QUANTITY * (1 - OD.DISCOUNT))
	) AS REVENUE
FROM
	PRODUCTS AS P
	JOIN ORDER_DETAILS AS OD ON P.PRODUCT_ID = OD.PRODUCT_ID
GROUP BY
	PRODUCT_NAME
ORDER BY
	REVENUE DESC
LIMIT
	10;

---PROFIT BY CATEGORY---

SELECT
	C.CATEGORY_NAME,
	ROUND(
		SUM((OD.UNIT_PRICE - P.UNIT_PRICE) * OD.QUANTITY)::NUMERIC,
		2
	) AS PROFIT
FROM
	ORDER_DETAILS AS OD
	JOIN PRODUCTS AS P ON OD.PRODUCT_ID = P.PRODUCT_ID
	JOIN CATEGORIES AS C ON P.CATEGORY_ID = C.CATEGORY_ID
GROUP BY
	CATEGORY_NAME
ORDER BY
	PROFIT DESC;


--SHIPPER PERFORMANCE--

SELECT
	S.COMPANY_NAME AS SHIPPER,
	COUNT(O.ORDER_ID) AS TOTAL_ORDERS
FROM
	ORDERS AS O
	JOIN SHIPPERS AS S ON O.SHIP_VIA = S.SHIPPER_ID
GROUP BY
	COMPANY_NAME
ORDER BY
	TOTAL_ORDERS DESC;

--3--

--CUSTOMER RFM--
SELECT
	C.CUSTOMER_ID,
	C.COMPANY_NAME,
	MAX(O.ORDER_DATE) AS LAST_ORDER_DATE,
	COUNT(O.ORDER_ID) FREQUENCY,
	ROUND(
		SUM(OD.UNIT_PRICE * OD.QUANTITY * 1 - (OD.DISCOUNT))::NUMERIC,
		2
	) AS MONETARY_VALUE
FROM
	CUSTOMERS AS C
	JOIN ORDERS AS O ON C.CUSTOMER_ID = O.CUSTOMER_ID
	JOIN ORDER_DETAILS AS OD ON O.ORDER_ID = OD.ORDER_ID
GROUP BY
	C.CUSTOMER_ID,
	COMPANY_NAME
ORDER BY
	MONETARY_VALUE DESC;


	--REVENUE GROWTH BY YEAR--

	WITH
	YEARLY_SALES AS (
		SELECT
			EXTRACT(
				YEAR
				FROM
					O.ORDER_DATE
			) AS YEAR,
			SUM(OD.UNIT_PRICE * OD.QUANTITY * (1 - OD.DISCOUNT)) AS REVENUE
		FROM
			ORDERS AS O
			JOIN ORDER_DETAILS AS OD ON O.ORDER_ID = OD.ORDER_ID
		GROUP BY
			YEAR
	)
SELECT
	YEAR,
	ROUND(REVENUE::NUMERIC, 2) AS REVENUE,
	ROUND(
		(
			(
				REVENUE - LAG(REVENUE) OVER (
					ORDER BY
						YEAR
				)
			) / NULLIF(
				LAG(REVENUE) OVER (
					ORDER BY
						YEAR
				),
				0
			) * 100
		)::NUMERIC,
		2
	) AS GROWTH_PERCENT
FROM
	YEARLY_SALES
ORDER BY
	YEAR;


--REPEAT CUSTOMER RATE--
WITH
	CUSTOMER_ORDERS AS (
		SELECT
			CUSTOMER_ID,
			COUNT(ORDER_ID) AS ORDER_COUNT
		FROM
			ORDERS
		GROUP BY
			CUSTOMER_ID
	)
SELECT
	ROUND(
		(
			COUNT(
				CASE
					WHEN ORDER_COUNT > 1 THEN 1
				END
			)::DECIMAL / COUNT(*) * 100
		),
		2
	) AS REPEAT_CUSTOMER_PERCENT
FROM
	CUSTOMER_ORDERS;


	--MONTHLY AVERAGE ORDER VALUE--
	SELECT
	DATE_TRUNC('month', O.ORDER_DATE) AS MONTH,
	ROUND(
		SUM(OD.UNIT_PRICE * OD.QUANTITY * (1 - OD.DISCOUNT))::NUMERIC / COUNT(DISTINCT O.ORDER_ID),
		2
	) AS AVG_ORDER_VALUE
FROM
	ORDERS AS O
	JOIN ORDER_DETAILS AS OD ON O.ORDER_ID = OD.ORDER_ID
GROUP BY
	MONTH
ORDER BY
	MONTH;
